spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
          content-type: application/json
        packlabel-out-0:
          destination: order-dispatched
          group: ${spring.application.name}
          content-type: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
server:
  port: 9003


